-- SQLite
INSERT into product(title, description, price, image) VALUES('Shawarma classic', 'Classic shawarma Chicken shawarma, also known as chicken tikka or chicken Tikka, is a popular Indian dish made from chicken cutlet (tikka) wrapped in pita bread and then grilled. It is often served with a spicy sauce or salad.',  100, 'shawarma4.jpg');
INSERT into product(title, description, price, image) VALUES('Innovative shawarma', 'In short, Innovative shawarma is an invention of the year that can be found in every restaurant but is much more expensive than shawarmas that were made by people.',  150, 'shawarma5.jpg');
INSERT into product(title, description, price, image) VALUES('Shawarma with pepper', 'Shawarma with pepper is a dish that combines the taste and healthiness of shawarma with the healthiness and taste of pepper.',  130, 'shawarma6.jpg');
INSERT into product(title, description, price, image) VALUES('Long shawarma', 'Long shawarma is a dish consisting of a flat slab of lamb meat with a variety of vegetables, such as red pepper, cucumbers, tomatoes, potatoes, onion and herbs.',  190, 'shawarma7.jpg');
INSERT into product(title, description, price, image) VALUES('Nachos shawarma', 'Nachos shawarma is a sandwich that is made on a plate with a hole in it, in which the bread is soaked in an oil-based sauce, and then it is dipped in lard.',  140, 'shawarma8.jpg');
INSERT into product(title, description, price, image) VALUES('Shawarma with onions', 'Get shawarma at a fast food restaurant, put it into a bag, put the bag in the freezer, then take a shawarma from the bag and put it in a sandwich, then put the sandwich in the fridge.',  100, 'shawarma9.jpg');
INSERT into product(title, description, price, image) VALUES('Small shawarma', 'Small shawarma is better than large hushpuppies.',  60, 'shawarma10.jpg');
INSERT into product(title, description, price, image) VALUES('Shawarma with cheese', 'Shawarma with cheese is a piece of meat, wrapped in pita bread, cooked in a special way, and then eaten with your fingers.',  200, 'shawarma11.jpg');
INSERT into product(title, description, price, image) VALUES('Shawarma with extra chili', 'Shawarma with extra chili sauce, shish kebab with ketchup, and a chicken leg with cheese are some of the most popular dishes at the local sandwich shop.',  140, 'shawarma12.jpg');
INSERT into product(title, description, price, image) VALUES('Shawarma with shrimps', 'Shawarma with shrimps. To be or not to be.',  500, 'shawarma13.jpg');